/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.foosoft.shipper.api;

public interface Plugin {
	public interface Factory {
	}

	public void start();

	public void stop();
}

